name: check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run [ci, lint, format]
        run: |
          npm ci
          npm run lint
          npm run format -- --check --no-write
